replicaCount: 3
image:
  repository: bioinformatic-security-suite
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  nodePort: 30001
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - bioinformatic-security-suite.example.com
  tls:
    - secretName: bioinformatic-security-suite-tls
      hosts:
        - bioinformatic-security-suite.example.com
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
