apiVersion: apps/v1
kind: Deployment
metadata:
  name: bioinformatic-security-suite-cloud-service
  labels:
    app: bioinformatic-security-suite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bioinformatic-security-suite
      service: cloud-service
  template:
    metadata:
      labels:
        app: bioinformatic-security-suite
        service: cloud-service
    spec:
      containers:
      - name: bioinformatic-security-suite-cloud-service
        image: bioinformatic-security-suite-cloud-service:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mongodb://db-service:27017"
        - name: JWT_SECRET
          value: "secret"
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
