apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: bioinformatic-security-suite-

resources:
  - microservices/edge-service/deployment.yaml
  - microservices/cloud-service/deployment.yaml
  - webgui/deployment.yaml
  - k8s/istio-config
  - k8s/cluster-config

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: bioinformatic-security-suite-edge-service
    path: microservices/edge-service/patches/replicas.yaml
